package:
  name: csmapi
  version: "0.1.0"

source:
  git_url: https://github.com/USGS-Astrogeology/CSM-Swig.git

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - cmake >=3.10
    - libcsm
    - python
    - swig
  host:
    - python
  run:
    - libcsm
    - python
    - numpy

test:
  imports:
    - csmapi
    
about:
  home: https://github.com/USGS-Astrogeology/CSM-Swig
  license: None
summary: "SWIG Wrapper to generate bindings to the Community Sensor Model"
