package:
  name: csmapi
  version: "1.0.1"

source:
  git_url: https://github.com/USGS-Astrogeology/CSM-Swig.git

build:
  detect_binary_files_with_prefix: True

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - cmake >=3.14
    - swig
    - python
  host:
    - python >= 3
  run:
    - csm
    - python 

test:
  imports:
    - csmapi

about:
  home: https://github.com/USGS-Astrogeology/CSM-Swig
  license: CC0-1.0
  license_file: LICENSE.md
  summary: "SWIG Wrapper to generate bindings to the Community Sensor Model"
